### ISSUE TITLE
Patching slingshot for e-add

### ISSUE THREAD

**Issue by varlesh** [varlesh/elementary-add#19]
@inpr1se For better looking need add patching slingshot on PPA
How do it:
- Download sources from [Daily eOS PPA](https://launchpad.net/~elementary-os/+archive/ubuntu/daily/+packages?field.name_filter=slingshot&field.status_filter=published&field.series_filter=)
- Patch:
```
#/bin/bash
sed -i 's|5|3|g' org.pantheon.desktop.slingshot.gschema.xml
sed -i 's|64|48|g' org.pantheon.desktop.slingshot.gschema.xml
sed -i 's|icon, 64,|icon, 48,|g' src/Backend/App.vala
sed -i 's|64|48|g' src/Widgets/AppEntry.vala
```
- Up version, for example slingshot-launcher_0.9.1

**Comment by varlesh** [comment]
@inpr1se 感謝

**Comment by inpr1se** [comment]
:v:
