### ISSUE TITLE
Indicators support?

### ISSUE THREAD

**Issue by bil-elmoussaoui** [varlesh/elementary-add#3]
Hello,
i would like to ask you to add some more indicators status/panels
- [ ] Variety 
- [ ] Viber (its hardcoded but can be fixed by patching sni-qt 
- [ ] Grive ( Google drive indicator)

If you want more informations about that! i would be happy to help
thanks

**Comment by varlesh** [comment]
Viber not support tray in eOS, not needed. 
grive-tools & variety will be added to extra.

**Comment by bil-elmoussaoui** [comment]
I know this already closed; but i tried the variety indicator icon, and the icon is so small? 
![screenshot from 2015-04-02 21 49 09](https://cloud.githubusercontent.com/assets/7660997/6972165/2c88bc4c-d982-11e4-8bed-58827509923c.png)

**Comment by varlesh** [comment]
Fixed on 0.2.9 relise on ppa.
