### ISSUE TITLE
Pushbullet indicator support

### ISSUE THREAD

**Issue by bil-elmoussaoui** [varlesh/elementary-add#6]
Hello,

I would like to ask you to support Pushbullet indicator support (the application icon and the indicator ones)
For the application icon : unfortunately its hardcoded,  
the desktop file : extras-pushbullet-indicator.desktop
the icon line : Icon = /opt/extras.ubuntu.com/pushbullet-indicator/share/pushbullet-indicator/icons/pushbullet-indicator.svg

For the indicator icon are in this zip file : https://www.dropbox.com/s/npn9g0mxrm5pxi3/pushbullet.tar.gz?dl=0
the icons are : the pushbullet-indicator.svg is the app icon 
![screenshot from 2015-04-02 21 31 21](https://cloud.githubusercontent.com/assets/7660997/6971835/a15740e6-d97f-11e4-98bd-b7576407512a.png)

**Comment by varlesh** [comment]
Added to "extra"!
