### ISSUE TITLE
edit-find-symbolic icon fix

### ISSUE THREAD

**Issue by bil-elmoussaoui** [varlesh/elementary-add#7]
Hello, 
I would like to ask you to fix an icon in the base icon of elementary theme
this icon is used as an indicator for synapse indicator 
and like you can see in this picture the icon is a little bigger
![screenshot from 2015-04-02 21 49 09](https://cloud.githubusercontent.com/assets/7660997/6972439/0601d6ce-d984-11e4-9ff7-948f27b9ab35.png)

the solution is over here : https://plus.google.com/116118568744093631670/posts/TvQMxoKpgK4 
if you are too lazy to take a look : "The icon should be a 16x16 icon on a 24x24 drawing space.﻿" 

Thanks!!

**Comment by varlesh** [comment]
Fixed!

**Comment by bil-elmoussaoui** [comment]
Wow ! Thanks for your hardwork

**Comment by bil-elmoussaoui** [comment]
I ve just got the update! The icon is looking a little bit small nop? 
![screenshot from 2015-04-02 23 58 57](https://cloud.githubusercontent.com/assets/7660997/6974589/45c04466-d994-11e4-9c47-fed10e16ce1d.png)

**Comment by varlesh** [comment]
Ok, fixed next release.
