### ISSUE TITLE
Clearer Readme

### ISSUE THREAD

**Issue by Foggalong** [varlesh/elementary-add#8]
The README references that it's a fork of elementary+ [here](https://github.com/varlesh/elementary-add#intention) but doesn't really say why it was forked or what the differences are between the two. It'd be a helpful addition for new users trying to decide between the two.

**Comment by varlesh** [comment]
Now its not a fork , but an independent project that uses some icons from elementary+ project.

**Comment by Foggalong** [comment]
That raises another question then - why not just submit the icons to elementary+? Isn't it just duplication of effort otherwise?

**Comment by varlesh** [comment]
My project have more icons ,  i created repository and I did a great job for this. Why should I submit icons elementary + ?

**Comment by Foggalong** [comment]
I could have sworn I'd responded to this at the time, but apparently not. Anyway:

While eAdd might have more individual icons, ePlus is more complete in terms of it's HiDPi support and size availability meaning it has more icons overall. Your icons are of great quality, but wouldn't it be great to work with loads of other developers to get them into a bigger, more wildly known collective where they can be properly filled out in all sizes?

I just love what you're doing here and would hate for all the effort to be duplicated :(

**Comment by varlesh** [comment]
Project temporarily frozen. I don't have time for HiDPi ))

**Comment by Foggalong** [comment]
Fair enough :)
